### ISSUE TITLE
Factory has for bidden read from Security ControlModule Address

### ISSUE THREAD

**Issue by SuperDev123-hub** [SoulWallet/soulwalletlib#86]
Hi, I am going to run the soulwalletlib project.
So I run below
- run geth test node locally
- run bundler by command which is provided on bundler repo
- run smartcontract by command which si provided on soul-wallet-smartcontract

However copy the code of package\sinternal-test\src\deploy.ts with address infos 
I got UserOpErrors: factory has forbidden read from "security Control module address". 
How can I solve this?

**Comment by jayden-sudo** [comment]
Yes, this issue exists.

The reason for the problem is in the [Bundler Source Code](https://github.com/eth-infinitism/bundler/blob/main/packages/bundler/src/parseScannerResult.ts#L304).

This is the storage access restrictions of ERC4337: https://eips.ethereum.org/EIPS/eip-4337#storage-associated-with-an-address

Soulwallet's contract currently supports adding modules/plugins during deployment, which can cause the issue you mentioned.

There are two ways to solve this problem:

1. Do not add modules/plugins during contract deployment, but add them after deployment is complete (this may affect user experience and security, e.g., social recovery module).
2. Use 'alternative-mempools' during deployment [link](https://eips.ethereum.org/EIPS/eip-4337#alternative-mempools), where specific bundlers can relax restrictions for certain audited contracts without compromising security (we plan to do this).

Of course, in your local testing environment, you can directly use the --unsafe parameter to disable the Bundler's storage check.

**Comment by SuperDev123-hub** [comment]
Thank you very much. This saves my time.
I just fixed it by using --unsafe parameter and I will check other options later.
